### ISSUE TITLE
Music Panel - Inversed Play / Pause Button

### ISSUE THREAD

**Issue by dallasco** [ioscreatix/Maize#67] opened 2017-10-01 16:52 UTC
After tapping play, then pause, the buttons inversed. Meaning the pause button would act as the play button, and vice versa. 

iOS 10.2 - 6S

No other control center tweaks are installed.

**Comment by andrewwiik** [comment] 2017-10-05 16:50
Duplicate of issues #56

**Closed as completed by andrewwiik** 2017-10-05 16:50 UTC
Labels: bug, duplicate
