### ISSUE TITLE
In landscape, modules (expanded & not) extend past screen [iPhone 6s Plus, 10.2]

### ISSUE THREAD

**Issue by aviairy** [ioscreatix/Maize#72] opened 2017-10-04 02:47 UTC
Vertically, modules are fine, but in landscape mode, the expanded modules go past the borders of the screen
>pic related
[IMG_7251.mp4.mov.zip](https://github.com/ioscreatix/Maize/files/1354452/IMG_7251.mp4.mov.zip)

**Comment by andrewwiik** [comment] 2017-10-05 16:48
Duplicate of issue #70

**Closed as completed by andrewwiik** 2017-10-05 16:48 UTC
Labels: bug, duplicate
