### ISSUE TITLE
Device Freeze On LS and HS unexpectedly 

### ISSUE THREAD

**Issue by maheshdj** [ioscreatix/Maize#27] opened 2017-08-18 02:42 UTC
iPhone 6 ios 10.2 after freeze only option to force reboot device

**Comment by andrewwiik** [comment] 2017-08-21 13:47
Not expierencing so hard to fix, marking as wont-fix for unable to reproduce

**Closed as completed by andrewwiik** 2017-08-21 13:47 UTC
Labels: wontfix

**Comment by maheshdj** [comment] 2017-08-21 15:36
Ok I'll tell once i get recreate method
